API_ID: 22707729
API_HASH: 933c666527206f88d614648be7eef6bb
BOT_TOKEN: 6631656081:AAE7hSDaFDjCbO2YOdk2oKEIEo9SizlqIgs


MONGO_URL: mongodb+srv://nicolscarlose:Nm280799@cluster0.dnjs8ld.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-10728.c276.us-east-1-2.ec2.cloud.redislabs.com
REDIS_PORT: 10728
REDIS_PASS: x74W12pjnT0lMAM6XGDvm5euRvsunKPb

SESSION_API_ID: 22707729
SESSION_API_HASH: 933c666527206f88d614648be7eef6bb
SESSION_STRING: 1AZWarzkBu3QYbFAaOfZrbYShnl96bVlXU1bXmCiY5r7OG0dFU9032ny7SNBCpsVWbFwZZJugyFD1m2ruXZV5GfGMfFLjqLXvLHY8UWXvnU6vy5gYaWksEP-21oadQUcD0xTIJpKr1dSuX0t50vgm5oa7oxpuQbqD3XgbA9UhxKCwfIsui0sSHEJzs3BhWRlIwutLGQg1HUz2lvB_NajEnQ6r5QetyhqGEHow5ZVQs4luiAokSHsOx0ornxVmmPcgF8DyilpuKwSkXSsaE9wXLmxcm1nkRy4nyDYQ8DBs7okmrpyzacTLzTNoBA_XDq8FB8nCmMl1RMrNMWlUoqJ6-qtFoJGcjYE=

ADMINS: 
  - 5612890532

OWNER: 5612890532

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: roldexversechats 
# LOG_CHAT: 
LOG_CHAT: -1001821612043



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

